name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Renovate Bot GitHub Action
        uses: renovatebot/github-action@v39.2.1
        with:
          configurationFile: .github/renovate-config.js
        env:
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}